### ISSUE TITLE
pytest-bdd regex step definitions are not recognized

### ISSUE THREAD

**Issue by Diggypiggy** [rioj7/vscode-bdd-gotostep#3]
The extension seems to not recognize step definitions with regex for pytest-bdd.

Example:

`repo/bdd/features/.../sandbox.feature`

```
@sandbox

Feature: Sandbox Feature

    @SB01
    Scenario: Verify whatever you want to test
        Given this step prepares some test data
        When I perform an action on the prepared data
        Then I validate the results of the performed <action>

        Examples:
            | action  |
            | action1 |
            | action2 |
```

`repo/bdd/step_defs/.../test_sandbox.py`

```
from pytest_bdd import scenarios, given, when, then
from pytest_bdd.parsers import re
scenarios('../../features/.../sandbox.feature')

@given(re(r"^this step prepares some test data$"))
def preparation_step() -> None:
    pass

@when(re(r"^I perform an action on the prepared data$"))
def action_step() -> None:
    pass

@then(re(r"^I validate the results of the performed (?P<action>action1|action2)$"))
def verification_step(action) -> None:
    pass
```

Questions:
Does the extension:
- have dependences on other extensions like Cucumber Support?
- support navigation to helper files which are imported to conftest.py and include common step definitions for a group of test_xxx.py files?

**Comment by rioj7** [comment]
@Diggypiggy  try v1.0.0 

If your python step files with `common step definitions` are found with the `bdd-gotostep.include` glob setting, the steps should be found

There is no dependences on other extensions.
What do you expect the extension to do with Cucumber Support?

**Comment by Diggypiggy** [comment]
Thanks for your response.
Well, testing for specific files and checking the logs I managed to identify 3 issues for my case.

1. Example parameters are not identified. 'Then' step in the description is not recognized because of `<action>`. If I replace it with action1, it works.
2. Backslashes in step definitions result to syntax error. I use backslashes to escape double quotes in the step.

**Example:**
Feature:
`Then I ensure that the "Barrier" switch is disabled`

Step Definition:
```
@then(re(r"^I ensure that the \"(?P<feature>Barrier|Login|Domain)\" switch is disabled$"), converters={'feature': str})
def switch_is_disabled(feature: str) -> None:
```

Console Error:
[rioj7.vscode-bdd-gotostep]Invalid regular expression: /I ensure that the \/i: \ at end of pattern

3. The extension does not escape errors occurred while searching the steps(syntax errors at least).  If I search for a step that otherwise would be recognized, but `bdd-gotostep.include` path includes a case of issue (2), then the related syntax error is produced in the logs and I get step not found. So searching does not skip the problematic case to continue finding the step I was looking for. This is the actual reason I could not navigate to any step definition.

As for your question, I just wanted to ensure that there is no conflict with other extensions and that `bdd-gotostep` does not need other extensions as dependency to work properly. Thanks for your answer.

**Comment by rioj7** [comment]
@Diggypiggy Oops the `then <action>` is the line I did not test.

I will modify the search regex to handle escaped characters, but for double quotes it is not needed to escape them if you use the `"""` or `'''` or `'` as string literal markers:

```none
@then(re(r"""^I ensure that the "(?P<feature>Barrier|Login|Domain)" switch is disabled$""")

@then(re(r'''^I ensure that the "(?P<feature>Barrier|Login|Domain)" switch is disabled$''')

@then(re(r'^I ensure that the "(?P<feature>Barrier|Login|Domain)" switch is disabled$')
```

**Comment by rioj7** [comment]
@Diggypiggy 

> 1. Example parameters are not identified,  'Then' step in the description is not recognized because of <action>

The following step line 

```none
@then(re(r"^I validate the results of the performed (?P<action>action1|action2)$"))
```

The string is extracted and the `^$` are removed resulting in:

```none
I validate the results of the performed (?P<action>action1|action2)
```

Now the named capture group is replaced with `.*?`

```none
I validate the results of the performed .*?
```

This is the regular expression tested on feature lines and will match the line under the cursor:

```none
Then I validate the results of the performed <action>
```

In my test VSC it will go to the correct step if I press F12 on the `Then` feature line.

**Comment by Diggypiggy** [comment]
@rioj7 Thank you so much for the interest and support.

Regarding the triple quotes, unfortunately the framework is quit big so changing several step definitions and testing requires a lot of effort that I was not allowed to take. Thanks for the suggestion though.

Regarding the step with parameters `Then I validate the results of the performed <action>`
I am surprised that you fixed it, it looks quite challenging to me considering that different `<action>` examples may lead to different step definitions.
But even if it cannot handle this case it is still very useful to me.
Again, thanks a lot!

**Comment by rioj7** [comment]
@Diggypiggy try v1.0.1 it should search steps with backslashes and show a QuickPick if multiple steps match, and report steps that result in bad Regex object but continue search

**Comment by Diggypiggy** [comment]
> @Diggypiggy try v1.0.1 it should search steps with backslashes and show a QuickPick if multiple steps match, and report steps that result in bad Regex object but continue search

@rioj7 I tried v1.0.1 in my framework and everything works apart from the 1st issue I mentioned and you described the solution in this [comment](https://github.com/rioj7/vscode-bdd-gotostep/issues/3#issuecomment-2485862780)
 Step definition is still not found when there is a variable in the feature step. Example parameters are not recognized. I tried several things but still no luck.

```
Scenario Outline: Verify whatever you want to test
    Then I validate the "results" of the performed <action> action

    Examples:
        | action  |
        | action1 |
        | action2 |

@then(re(r"""^I validate the "results" of the performed (action1|action2) action$"""))
```
If I put an example in the step itself it works:
`Then I validate the "results" of the performed action1 action`

Also please check the below log:
![image](https://github.com/user-attachments/assets/fece1b8c-7652-4e32-adc0-ae96f779ba2d)

There are still 2 syntax errors for 2 complex step definitions I have but this is minor to me.
For what I am wondering is the below warnings and errors I keep getting which I do not remember having last time I checked. Are those produced by the extension? If yes could this be a long term issue?

Everything else is working as expected!
By the way the dropdown selection when there is more than 1 result is really cool!

**Comment by Diggypiggy** [comment]
> <action>

Oh now I see, the example must be a variable in the step definition as well in order to work. Ok.
thanks

**Comment by rioj7** [comment]
@Diggypiggy 

The `[AsyncPostMessage]` logs are not from this extension.

----

If you want to show something from the Developer Console or the VSC messages please Copy/Paste the text, it makes recreating the issue a lot easier.

----

In the OP you used:

```none
Then I validate the results of the performed <action>

@then(re(r"^I validate the results of the performed (?P<action>action1|action2)$"))
```

That works.

It turns out that you have

```none
Then I validate the results of the performed <action>

@then(re(r"""^I validate the "results" of the performed (action1|action2) action$"""))
```

The string is a valid regex but it will not match the feature line raw, how the extension works.
It will match when the test runner fills in the `<action>` field from the table.

----

Why do you enumerate all possible cases in the step definition?
If there is a new case you have to modify multiple places.
Won't a version like this work:

```none
@when(re(r"^I retrieve the \"(?P<name>.*?)\" sharing policy of the tenant$"))

@when(re(r"^there is a trusted share created for a (?P<itemtype>.*?) with an? (?P<recipients_type>.*?) recipient$"))
```

Is the line:

```none
I retrieve the "AUTOMATION ONLY default policy" sharing policy of the tenant
```

really a possible feature line?

----

I will convert every top-level capturing group to a `.*?` so it will match a feature line, and it will keep track of escaped characters and balanced `()`'s

**Comment by Diggypiggy** [comment]
`If you want to show something from the Developer Console or the VSC messages please Copy/Paste the text, it makes recreating the issue a lot easier.`

You're right sorry..

` It will match when the test runner fills in the <action> field from the table.`
About this, I figured it out after all. I was testing many cases according to definitions we already use, to check for issues. So the alternatives I am sharing with you are just different cases of other existing step definitions.

In general our framework has more than 3000 scenarios resulting to hundreds of steps and many of them are very similar each other. So I guess the initial idea was to make them more strict to avoid conflicts. 
All the alternatives you propose are valid and most probably can be applied in our framework but unfortunately it takes time to investigate, fix and test and I did not get the approval to do so for only having the navigation ability.

However as I mentioned the remaining issues are minor and we can live with them I guess. At this point I do not want to push either you or the management further. I am happy with the changes you have done already. Thank you so much!

**Comment by rioj7** [comment]
@Diggypiggy That is quite a testing suite. Then a **Jump To Step** saves a lot of searching.

Try v1.0.2, it should now find the steps from the picture (complex step regex) and the `(action1|action2)` is now part of the multiple match or jumped to if the only one.

**Comment by Diggypiggy** [comment]
@rioj7 Seriously, I have no words; I’m really grateful. 
I still see 1.0.1 as the latest version though, in the marketplace. I'll check again tomorrow.

**Comment by rioj7** [comment]
@Diggypiggy Sometimes the publish is not getting through. I have published again and now I see v1.0.2 in the market place

**Comment by Diggypiggy** [comment]
@rioj7 Just giving some feedback since you have worked for v1.0.2 (no actions needed though).

The latest changes do not seem to work. (action1|action2) without variable. It works for different variable name(other than `<action>`) though. `(?P<blabla>action1|action2)`

I will also paste the errors since you asked the 1st time.

`Error creating RegExp from: @when(re(r"^I retrieve the \"(?P<name>Access Link & OTP enabled \(USED IN AUTOMATION\)|AUTOMATION ONLY default policy)\" sharing policy of the tenant$"), converters={'name': str}, target_fixture='sharing_policy') - SyntaxError: Invalid regular expression: /I retrieve the \".*?|AUTOMATION ONLY default policy)\" sharing policy of the tenant/i: Unmatched ')'`

`@when(re(r"^I retrieve the \"(?P<name>Access Link & OTP enabled \(USED IN AUTOMATION\)|AUTOMATION ONLY default policy)\" sharing policy of the tenant$"), converters={'name': str}, target_fixture='sharing_policy')
`

`Error creating RegExp from: @given(re(r"^there is a trusted share created for a (?P<item_type>file|(non-empty |)folder) with an? (?P<recipients_type>external|internal|non-registered) recipient$"), converters={'item_type': str, 'recipients_type': str}, target_fixture='share') - SyntaxError: Invalid regular expression: /there is a trusted share created for a .*?folder) with an? .*? recipient/i: Unmatched ')'`

`@given(re(r"^there is a trusted share created for a (?P<item_type>file|(non-empty |)folder) with an? (?P<recipients_type>external|internal|non-registered) recipient$"), converters={'item_type': str, 'recipients_type': str}, target_fixture='share')
`
I suspect the nested parenthesis is the issue for those cases.

**Comment by rioj7** [comment]
@Diggypiggy 

In the feature file I have:

```none
Then I validate the results of the performed <action>
```

`<action>` takes its values from the table

If I press `F12` (Goto step) I get a QuickPick for the following steps defined in a `.py` file

```python
@then(re(r"^I validate the results of the performed (?P<action>action[12])$"))
@then(re(r"^I validate the results of the performed (?P<action>action[3-9])$"))
@then(re(r"""^I validate the results of the performed (action1|action2)$"""))
```

> The latest changes do not seem to work. (action1|action2) without variable.

Can you give an example of the feature line and the step line you want to match but are not yet matched?
Do you use custom variable separators in the steps?
```python
@then(re(r"""^I validate the results of the performed <action>$"""))
```

----

Are the steps that produced the errors now found using matching feature lines?

**Comment by Diggypiggy** [comment]
Wow! did you change something in the same version? It was not working before I send the above comment. I verified it with a colleague of mine.
Anyway it doesn't matter... 
The latest changes produced a new error but I can change those steps easily. 
Finally we can navigate to step definitions AND without errors! Thanks man, you nailed it!

**Comment by rioj7** [comment]
@Diggypiggy  That is good to here but you make me curious what valid regex you have constructed that my simple parenthesis counter parser fails ;-) and now flags as error.

**Comment by Diggypiggy** [comment]
@rioj7  You asked for it, you got it :P 

`Error creating RegExp from: @given(re(r"^I have set the timeout period of the \"External user inactivity timeout\" device policy to (?P<value>\d+) min(s)?$"), converters={'value': int}) - SyntaxError: Invalid regular expression: /I have set the timeout period of the \"External user inactivity timeout\" device policy to .*? min.*??/i: Nothing to repeat`

This is the problem. `min(s)?` is not recognized. `min(s)` is ok. `mins?` is ok too. The combination produces the error. I will simply replace those cases with `mins?` since it's almost the same.

**Comment by rioj7** [comment]
@Diggypiggy If you make it a non-capture group you can leave the `()`, what you don't capture you don't pass to the function as an argument, or add an additional capture group surrounding the problem, the top-level capture group will be replaced with `.*?`:

```python
@given(re(r"^I have set the timeout period of the \"External user inactivity timeout\" device policy to (?P<value>\d+) min(?:s)?$"), converters={'value': int})

@given(re(r"^I have set the timeout period of the \"External user inactivity timeout\" device policy to (?P<value>\d+) min((s)?)$"), converters={'value': int})
```

I don't think it is needed to add logic to detect if there is a qualifier `*+?{}` after a top-level capture group, or I can use the replacement `(?:.*?)` (non capture groups are a little bit faster). It is the same as with `#define` in C/C++: always add `()` surrounding the macro to prevent unwanted operator precedence logic.

**Comment by Diggypiggy** [comment]
@rioj7 To be honest I did not follow the last part of your comment but the outcome is that everything works perfect without changing my steps at all... 
I really appreciate all the things you've done for me. I was never expecting all these the day I opened the ticket. Best support ever!💯
